using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Named after an external unmanaged type.", Scope = "type", Target = "~T:LibUISharp.Native.LibuiLibrary.uiAlign")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Named after an external unmanaged type.", Scope = "type", Target = "~T:LibUISharp.Native.LibuiLibrary.uiAt")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Named after an external unmanaged type.", Scope = "type", Target = "~T:LibUISharp.Native.LibuiLibrary.uiAttributeType")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Named after an external unmanaged type.", Scope = "type", Target = "~T:LibUISharp.Native.LibuiLibrary.uiDrawBrushType")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Named after an external unmanaged type.", Scope = "type", Target = "~T:LibUISharp.Native.LibuiLibrary.uiDrawFillMode")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Named after an external unmanaged type.", Scope = "type", Target = "~T:LibUISharp.Native.LibuiLibrary.uiDrawLineCap")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Named after an external unmanaged type.", Scope = "type", Target = "~T:LibUISharp.Native.LibuiLibrary.uiDrawLineJoin")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Named after an external unmanaged type.", Scope = "type", Target = "~T:LibUISharp.Native.LibuiLibrary.uiDrawTextAlign")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Named after an external unmanaged type.", Scope = "type", Target = "~T:LibUISharp.Native.LibuiLibrary.uiExtKey")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Named after an external unmanaged type.", Scope = "type", Target = "~T:LibUISharp.Native.LibuiLibrary.uiForEach")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Named after an external unmanaged type.", Scope = "type", Target = "~T:LibUISharp.Native.LibuiLibrary.uiModifiers")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Named after an external unmanaged type.", Scope = "type", Target = "~T:LibUISharp.Native.LibuiLibrary.uiTextItalic")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Named after an external unmanaged type.", Scope = "type", Target = "~T:LibUISharp.Native.LibuiLibrary.uiTextStretch")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Named after an external unmanaged type.", Scope = "type", Target = "~T:LibUISharp.Native.LibuiLibrary.uiTextWeight")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Named after an external unmanaged type.", Scope = "type", Target = "~T:LibUISharp.Native.LibuiLibrary.uiUnderline")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Named after an external unmanaged type.", Scope = "type", Target = "~T:LibUISharp.Native.LibuiLibrary.uiUnderlineColor")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Named after an external unmanaged type.", Scope = "type", Target = "~T:LibUISharp.Native.LibuiLibrary.uiWindowResizeEdge")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Named after an external unmanaged type.", Scope = "type", Target = "~T:LibUISharp.Native.LibuiLibrary.uiAreaDrawParams")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Named after an external unmanaged type.", Scope = "type", Target = "~T:LibUISharp.Native.LibuiLibrary.uiAreaHandler")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Named after an external unmanaged type.", Scope = "type", Target = "~T:LibUISharp.Native.LibuiLibrary.uiAreaKeyEvent")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Named after an external unmanaged type.", Scope = "type", Target = "~T:LibUISharp.Native.LibuiLibrary.uiAreaMouseEvent")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Named after an external unmanaged type.", Scope = "type", Target = "~T:LibUISharp.Native.LibuiLibrary.uiDrawBrush")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Named after an external unmanaged type.", Scope = "type", Target = "~T:LibUISharp.Native.LibuiLibrary.uiDrawBrushGradientStop")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Named after an external unmanaged type.", Scope = "type", Target = "~T:LibUISharp.Native.LibuiLibrary.uiDrawMatrix")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Named after an external unmanaged type.", Scope = "type", Target = "~T:LibUISharp.Native.LibuiLibrary.uiDrawStrokeParams")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Named after an external unmanaged type.", Scope = "type", Target = "~T:LibUISharp.Native.LibuiLibrary.uiDrawTextLayoutParams")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Named after an external unmanaged type.", Scope = "type", Target = "~T:LibUISharp.Native.LibuiLibrary.uiFontDescriptor")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Named after an external unmanaged type.", Scope = "type", Target = "~T:LibUISharp.Native.LibuiLibrary.uiInitOptions")]

[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Transparent")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Black")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Navy")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.DarkBlue")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.MediumBlue")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Blue")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.DarkGreen")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Green")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Teal")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.DarkCyan")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.DeepSkyBlue")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.DarkTurquoise")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.MediumSpringGreen")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Lime")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.SpringGreen")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Aqua")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Cyan")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.MidnightBlue")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.DodgerBlue")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.LightSeaGreen")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.ForestGreen")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.SeaGreen")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.DarkSlateGray")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.DarkSlateGrey")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.LimeGreen")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.MediumSeaGreen")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Turquoise")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.RoyalBlue")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.SteelBlue")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.DarkSlateBlue")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.MediumTurquoise")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Indigo")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.DarkOliveGreen")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.CadetBlue")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.CornflowerBlue")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.RebeccaPurple")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.MediumAquaMarine")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.DimGray")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.DimGrey")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.SlateBlue")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.OliveDrab")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.SlateGray")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.SlateGrey")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.LightSlateGray")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.LightSlateGrey")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.MediumSlateBlue")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.LawnGreen")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Chartreuse")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Aquamarine")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Maroon")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Purple")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Olive")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Gray")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Grey")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.SkyBlue")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.LightSkyBlue")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.BlueViolet")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.DarkRed")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.DarkMagenta")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.SaddleBrown")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.DarkSeaGreen")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.LightGreen")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.MediumPurple")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.DarkViolet")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.PaleGreen")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.DarkOrchid")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.YellowGreen")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Sienna")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Brown")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.DarkGray")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.DarkGrey")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.LightBlue")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.GreenYellow")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.PaleTurquoise")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.LightSteelBlue")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.PowderBlue")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.FireBrick")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.DarkGoldenRod")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.MediumOrchid")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.RosyBrown")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.DarkKhaki")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Silver")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.MediumVioletRed")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.IndianRed")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Peru")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Chocolate")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Tan")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.LightGray")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.LightGrey")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Thistle")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Orchid")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.GoldenRod")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.PaleVioletRed")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Crimson")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Gainsboro")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Plum")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.BurlyWood")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.LightCyan")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Lavender")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.DarkSalmon")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Violet")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.PaleGoldenRod")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.LightCoral")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Khaki")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.AliceBlue")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.HoneyDew")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Azure")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.SandyBrown")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Wheat")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Beige")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.WhiteSmoke")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.MintCream")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.GhostWhite")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Salmon")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.AntiqueWhite")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Linen")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.LightGoldenRodYellow")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.OldLace")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Red")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Fuchsia")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Magenta")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.DeepPink")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.OrangeRed")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Tomato")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.HotPink")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Coral")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.DarkOrange")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.LightSalmon")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Orange")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.LightPink")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Pink")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Gold")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.PeachPuff")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.NavajoWhite")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Moccasin")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Bisque")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.MistyRose")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.BlanchedAlmond")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.PapayaWhip")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.LavenderBlush")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.SeaShell")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Cornsilk")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.LemonChiffon")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.FloralWhite")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Snow")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Yellow")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.LightYellow")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.Ivory")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML Comment", Justification = "Documentation to-be-done.", Scope = "member", Target = "LibUISharp.Drawing.Colors.White")]